### PR TITLE
Attempt to solve the "stuck in the corner" and endless horizontal/vertical rebound issues

### PR DESCRIPTION
**Pull request by patrick-assaf**

### CODE REVIEW

**Comment by eldenpark** [comment]
image

**Comment by eldenpark** [comment]
Still has that problem. Coud you confirm or upload the screenshot of gameplay?

**Comment by patrick-assaf** [comment]
Screen Shot 2020-06-22 at 9 02 58 PM

**Comment by eldenpark** [comment]
Looks like I have an old version of your branch `Patrick/UI`

**Comment by eldenpark** [comment]
Awesome trick here 👍

**Comment by eldenpark** [comment]
@patrick-assaf Looks like Game scene is colliding. I think it is caused by the four wedges on the corners you added. Could you possibly re-pull the `master` and copy paste those wedges again on to your change?

**Comment by patrick-assaf** [comment]
Sure thing! Let me give it another shot

**Comment by patrick-assaf** [comment]
Can you check it again? If it's still not showing up I'll just try another method

**Review by eldenpark — DISMISSED** [review]
👍

**Comment by eldenpark** [comment]
Works like a charm

**Comment by eldenpark** [comment]
Oh wait, it still has a conflict

**Review by eldenpark — CHANGES_REQUESTED** [review]
Conflicts

**Comment by patrick-assaf** [comment]
That's strange, I pulled the latest version of `master` right before making the changes

**Comment by eldenpark** [comment]
This is because I merged the other PRs which were opened after your PR onto `master`. I should have done yours the first as is it chronological, but didn't because I thought your PR still needs something to change (which is my fault)

**Comment by eldenpark** [comment]
Seems like people were all working on different parts of the project at the same time as you were working on this issue.

**Comment by patrick-assaf** [comment]
Don't worry about it too much haha just let me know if I should remake the changes at a later time.

**Pull request closed without merging**
