### PR TITLE
Added different scenes for each level and updated game over scene.

### PR DESCRIPTION
**Pull request by pspatel04**

### CODE REVIEW

**Comment by eldenpark** [comment]
This PR is in conflict. Could you deal with this? @pspatel04

**Review by eldenpark — CHANGES_REQUESTED** [review]
conflict - gameScene

**Comment by pspatel04** [comment]
> This PR is in conflict. Could you deal with this? @pspatel04

Yup. Working on it.

**Comment by eldenpark** [comment]
✅

**Pull request closed without merging**
