### PR TITLE
refactor: separate BallScript into different behavior objects

### PR DESCRIPTION
**Pull request by eldenpark**
- BallScript is renamed Ball.
- `Balls/` is defined and it has Ball-related files.
- Sprites and Textures are moved to `Resources/`. This is in order to
  make Resources available to load dynamically.
- Enum BallType is defined which the initial state is injected through
Unity.

### CODE REVIEW

**Review by JBeavans — APPROVED** [review]
Glanced over these. Doesn't seem too crazy.

**Review by gmoncada001 — APPROVED** [review]
Looks nice and clean! Nice job.

**Review by RuchaTambe — APPROVED** [review]
Looks good!

**Comment by eldenpark** [comment]
merge imminent

**Pull request merged**
